#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: nginx-ingress
  labels:
    chart_group: nginx-ingress
spec:
  releaseName: ic-nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      version: 4.0.15
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 5m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: nginx-ingress-static-overrides
      valuesKey: nginx-ingress-static-overrides.yaml
    - kind: Secret
      name: nginx-ingress-system-overrides
      valuesKey: nginx-ingress-system-overrides.yaml
