#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

namespace: kube-system
resources:
  - helmrelease.yaml
secretGenerator:
  - name: nginx-ingress-static-overrides
    files:
      - nginx-ingress-static-overrides.yaml
  - name: nginx-ingress-system-overrides
    files:
      - nginx-ingress-system-overrides.yaml
generatorOptions:
  disableNameSuffixHash: true
