---
- project:
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-nginx-ingress-controller-tox-py27
        - k8sapp-nginx-ingress-controller-tox-py39
        - k8sapp-nginx-ingress-controller-tox-flake8
        - k8sapp-nginx-ingress-controller-tox-pylint
        - k8sapp-nginx-ingress-controller-tox-bandit
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-nginx-ingress-controller-tox-py27
        - k8sapp-nginx-ingress-controller-tox-py39
        - k8sapp-nginx-ingress-controller-tox-flake8
        - k8sapp-nginx-ingress-controller-tox-pylint
        - k8sapp-nginx-ingress-controller-tox-bandit
    post:
      jobs:
        - stx-nginx-ingress-controller-armada-app-upload-git-mirror

- job:
    name: k8sapp-nginx-ingress-controller-tox-py27
    parent: tox
    description: |
      Run py27 test for k8sapp-nginx-ingress-controller
    nodeset: ubuntu-xenial
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/update
      - starlingx/utilities
    files:
      - python-k8sapp-nginx-ingress-controller/*
    vars:
      tox_envlist: py27
      tox_extra_args: -c python-k8sapp-nginx-ingress-controller/k8sapp_nginx_ingress_controller/tox.ini

- job:
    name: k8sapp-nginx-ingress-controller-tox-py39
    parent: tox-py39
    description: |
      Run py39 test for k8sapp-nginx-ingress-controller
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/update
      - starlingx/utilities
    files:
      - python-k8sapp-nginx-ingress-controller/*
    vars:
      tox_envlist: py39
      python_version: 3.9
      tox_extra_args: -c python-k8sapp-nginx-ingress-controller/k8sapp_nginx_ingress_controller/tox.ini

- job:
    name: k8sapp-nginx-ingress-controller-tox-flake8
    parent: tox
    description: |
      Run flake8 test for k8sapp-nginx-ingress-controller
    files:
      - python-k8sapp-nginx-ingress-controller/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c python-k8sapp-nginx-ingress-controller/k8sapp_nginx_ingress_controller/tox.ini

- job:
    name: k8sapp-nginx-ingress-controller-tox-pylint
    parent: tox
    description: |
      Run pylint test for k8sapp-nginx-ingress-controller
    nodeset: ubuntu-xenial
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/update
      - starlingx/utilities
    files:
      - python-k8sapp-nginx-ingress-controller/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python-k8sapp-nginx-ingress-controller/k8sapp_nginx_ingress_controller/tox.ini

- job:
    name: k8sapp-nginx-ingress-controller-tox-bandit
    parent: tox
    description: |
      Run bandit test for k8sapp-nginx-ingress-controller
    files:
      - python-k8sapp-nginx-ingress-controller/*
    vars:
      tox_envlist: bandit
      tox_extra_args: -c python-k8sapp-nginx-ingress-controller/k8sapp_nginx_ingress_controller/tox.ini

- job:
    name: stx-nginx-ingress-controller-armada-app-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/nginx-ingress-controller-armada-app to
      github.com/starlingx/nginx-ingress-controller-armada-app
    vars:
      git_mirror_repository: starlingx/nginx-ingress-controller-armada-app
    secrets:
      - name: git_mirror_credentials
        secret: stx-nginx-ingress-controller-armada-app-github-secret
        pass-to-parent: true

- secret:
    name: stx-nginx-ingress-controller-armada-app-github-secret
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      ssh_key: !encrypted/pkcs1-oaep
        - 4GoY5jRmFQndeGi6uQYVYGlA06yOZoKFTA4TMK5+wSfne2Ic+fKQxnUGN9AqDURT0PsUX
          nR4uZqxANdNP03Yhfi0+nq1CTxA+aNk6jji1qwKvGjbhtikA1ZqW8RsEOpl5J7uE9rRpZ
          OvyBbVYs2K60rj88IVzEJgdiX2KV3mWGnf1fmoL7LNDWjjtGATOFftysZsclBmpDAR/yG
          f7i52P2kZMr9ufZQup+wcK1zOSUs6AwxPHHYn7VqT5BOenmIciEXm8HjwbK9IKmqQfXYU
          1t7FnGBlDIF2DreQCmEWtwQqgm45Y2G/h71eN0sdIE+qW1f2UrA4sGQvmG3nWlgYKXQ8A
          LdiBbw4cCdc49c/jkvd46+3zCmpEpRsbD8JZ8oius4W+roLcFa/IPZBA/sCn7vUWnIwVi
          rBkqiTdNHKFqFQltSTEBD8vq82tLO2uwA4GBPD4tpxtMNOaJpbTq/vjXHvBZwXp9kRTzS
          cKeoyMGxX3lvy/tHMLx4FFCz5+w3yefhlXvllsBbQHHjEjmtLUDXMyAaExlC6+Vu0gQZW
          aP5467oq+AP7nhMNV3xXHdbnWA/vCjAWRHTQ9+p+ptrZzYLuWbXES/UG5qA/a7Tfpi9sn
          uyLeNrqOUJ7Bd3oox8pDeWy1VLD7qc3C3/vxDoznQCPmChogioCBPYo2SWPgcc=
        - 5jYr9cuUyTEZkdYK5JQu7ygW3Mto9M2UHl88M63RHmIcY/tKINP7Skc/WIG8hKiqY+SSG
          70S5WCci8Boe8h0mrxaBYQNYvDGuL+0a9DQAGfree6+QmzNbzH62Ff0S769xY/P9IavNU
          WDGMIl3Kg3+el5Lg8MBo+RlclPRe+DquaK1YVPpheB6N5amHGI/c3nOxOl2KIATCHY7FA
          DcowFo7Dm80PHLkiR0eLO23jPAlNWlKrdlG6Af5cGu7j8LKQR6xA+bh0JJGzgYtP8iqrU
          +sL1h7jcA+urNtbc/fiWfrEdwv6WHiKncHOiMqzqmmd+o9gbTbXaxeBGcIRpXtNAXyKrs
          2I6DmfEas5gI9kzVFVgWx60gIpC6PGOQ2n5yggDIsy8g1P9oxDoz25u5BHvq2kRThmYif
          MBCLSnEujDEZSiUVVak+fuXFMEDKerTmryWMX6IJln08Fc2trTTqeFW+H+1uHDVq3Iz/a
          61ORAJQkI9CL0CorbPaQfp2nRDAlNh2HcBpyUmTCWyCelEwlE3o6zNIwtXX7E75r0LSL8
          LfT9a4ZoLUZvWrKl29/JaGOSOimPbzgWUX5ompKX7ZDyNbpmVdmA1TzCsChBxDsUh8TIx
          5NHcnMuPSYfnhNGwzkmXynMiQmTiFNvz5HzWQJCoRq71PWci3pVCVRljd/MyJ0=
        - TDysAbdA44oQOCG8sYy3hqNtHdnQdZXytR3azhANgQrBKK1AiagCDryNf65RNJp5T3b92
          DeD5ArmyqOPlp9tWDwRn0HeiOYLwlaTW5q9mZwtLNlA2x51Px0+GZLDv7fo7q2yf5DqtS
          hSb2RG911lQqPYWJx75yKCzku8Fhzf8iLWxiT+ahUQFXWlR0YpTzav85sNuf/bDTyMOlP
          YC6VIbdZGY0JHZRWuReb9LND+SNDa6j7uCSo0olb5kW5l7C75uVkWjIdHg4g+TIB5YOyn
          yzmmeJlaMNq5qg/QVFWvOxIhS4cdZtfSKpG+tN62DXasIGyjIRK+mH85EWQYfpgck9qtz
          F0NM68ME+rBfceqY6OfjOjPX9DSm5teBnVpMaITogGgCNXs1XF0PlLmkhKfRWA8f0mxFY
          yKU9xMxSdYTrXA5nSou4URAnvBHYPbMzSR6c7fMRWEwPSDbSQYWnCs051dt7i+X9fpEbs
          YuFBuY/HXMjThRqfF5cKQrFZ1nkuikoiHPZxvzOi7hnBnonUjJu7WKW7UWyx2/1N1pmll
          ONpEesfawJhzJBhOfOWe5ILfEtJQGjnGajsB51hFStK/M0CxgUvz6lL0g1qToLzFZqDiE
          rChzyqoIz2MILxL5lDNNmaX327YIckXwOa5iKQPy31h7SZPVzgH9AYHau7FPTg=
        - nAXKBIpd+FxThSArvLqAE1yQircvVaPVRIxY9G49b3HXbQyiXHhfGONoktkOl+Utvprqy
          Ht2Hdb4ODNkgIfPemBIpn/2UQ2usjFexDyW60yONqK9S+Le/QRerwnfaomYtOVHNz3bvP
          +YWKl6Dwb9d/36xc82wHRp+b9kzhR2KbyG7EcDUvOBsB/Dcnk2q9U+Q17MFEXl9alwJVK
          ifcypsbarSriRm/0vORFYQJ03YmkHLQPaniLK4Bhg2McOpV2ZaztoEF49tkomMIEzphVk
          G1c4r31sYLpKGuY6DIn4srC9AEuRhcdLudEQSqYY7ssEQFKMqhIQnNvYDEzkg2rijEgx8
          mdEFRWUqwiu22osf+IEiakjL9owODXPkg6bLs44y+IoEoyPaAx7jRx2P/SOssuJKqPqQ5
          8FuRhRgjHVXDnMdgM7EEajZK0xki0R4XPE+I0kr2T5mtEdV1sPFQ4H98ivNDOKaY9VqdH
          zUtTSBLkThF2IawVe2thmMsOnjWlAZJF7EC4uOn0+/KD6p1iPA8rYF2xbj1KO5PKmefZd
          7bQFuhGAMJJ8lhAG7XcNvnn0+hiRWWlBxMn1Kd2AROeQocr9QlMWRomdmkKqS804Q+YoZ
          izyXk9OyUGodaLaLodJ4mnPaedQqWZxfnvjA2n5Ao/SdPj/bv1A/DhM5vQ8QOg=
        - DtbppB/mYp3YJ3e9ifGyNkl8QorZjPBBduh+jbZvtC5OrItMayP/JQmTtothZ4iyQng9n
          AdSf2xMgofhlrqWSKYYYI54KsVHPozj7AlhvKh6quE+Ds1h5IAF5A97DSHx/b74ihnmJZ
          sp8WxNCr8bOSl3RLocFEbARAOH3PlKUTaIMaCLfAqw9vV+NhlMcNzynXWrTMxiPizlDBe
          4PjqceEA4J4LwDk5V9v6ErXF3qOEjlbSaSTiI7zIx4HdxBTysSIA0p9va+o+EhWx4x6TN
          V9juRuumhH9hLmDRImfbR0SfgwAo2DQdEhQESpTMD4bD3w+tAu/6GWFvfHF7vgCGLCs/1
          4nAqNlfi8IkacYxFxbBIchwbj5b2NfOfX47WO9qCQe/kLHj3Yf91vkTyroZkoye/J6P7W
          pbpIai5CpKJAc44ZYMw4nJH6y3GfgGU6dAZYwjRFB58AqbpT5ICoW0x5QM16bvFxRJuHI
          FptytPKxZ7Grtt1IBqmll6y7GomS6t3FSoCvn648/zLDjgOokbzroFAy6rPsBRJBmz2SC
          HNMeTYhcF1cR6dFvl9PzDlUzZ8/Wk86/gQxCluW/EJd4CEONdf1Kf1ppIWf3B4xyjl2N/
          KB543rWg5T4T4nMXaUOpP09QOxIxfOzsgXEDsSMpNN7bz/9x6wFGRdUNX1VEoo=
        - MzDDbgukw+ZofANLd3LJhtDLLUWKINS41zBx1HNGpApGyDhKUt72/DxEh/ZN39CtC0dp2
          cfaY0M+SYH3QUBNWotJiyiQIyV14k5iAVYP90WFFaVvkWReMh95ELu9HwTX2uwaZoMI6A
          5bXxl/Z1V+FsJGeuADVLKEFQC3+nmhSBlh3yEz0h/Kf8xJL368XHiklol8S1iRxYt47xU
          /cV7uwldHxIJrkVffzhf/jqVzBwgk7h5V6M7i/9IYHADMaOPWvTQgK9PZ2RktBY9TwpCw
          VYnahA4xHBwtMj9GWy2ecDUnSeV5H6PRrPF6QZke3z7W3WHRCfVFTjmvY2RNfJPOXXtcS
          u3QvmiCwpDZ96H6NLgxfkdRC+A9J1kjZAR27EwEYa7mH3uFFVtSpoMR1dPUEJ/+Kz/lJ5
          /xiTCppYwSIbHf++nvjBDj4dL9FbhhbhB4YdRL+1FUHOeWLODDN/cisO9YIXVCm3hffUQ
          o2rW1V9JtIMmc/GOD6wZ6AWbMDiX2OpLfIR0aHWKxvp1CD8AesBORK5KabG0ZAew0tz9b
          FI2M/nCUxskqWjw2bjuInuOTdFYQGzsrtMueeBu59Yx6VaHj2z0R4Jj6UD7f8MyS3l0tG
          vbXS0WgPEz8uA7diPtSOCjPOZzZ6ceeNWEh1KzuiEswGOgHkdwlN2SYelAASxM=
        - jIDbnJmzxhAo6nQiQVVXG8DMTrnqLkmXMvaWCrftNXRTYy89O3SJxM9Re/jwi9JA4mPNd
          DC2Qt3XgoQWvT9xGhRBJz7Gk9KXueetqhF76e2IZGPzsdvz6FDEv+tKBAN1nbdw5yXzpT
          AZLwt0ouw4/aPSB8i7/gYe3qVs0JB4ZF8DC1AjfZapAYTGOorqc/cEcZUI6mwR5EUOqe3
          w11hKa+9Rs9iwgOq+ua8BndBImPF/PFh5U0ZDiCh3bFNJcAxb41z8/GdS5cW0xrt25aNL
          toy6NJTW9c1LYC/Wjx+QQeNP6xT+JlFfCLJ3DmgNzVIIPdRNamgJHGtNXllZCDG4UvWzP
          Ry2rqITz0bmxCh7oKM9IpCj4IeVg5CP7C/wE0kTexiLo66oKgr26tZsEtZDPEgwjBi5Lm
          NH5B5vvXBkFbrC5QwYNB/jmZGwfygk4TL14kLzQnbQmsKeHQLduJAVhrt2sYVeCwbcOf3
          2JiiEt/rfUcgliKg8Rialqk9Mmczh//NZxyELye35ztPSLcnPBvH2g2KeYIsS1SKAIClZ
          +D8tXy75cuDP/EJ76U2bmmti7wZs3BcVnANj1Xe35zdcAn9+ByhFWrYtQJm9R5x2sur3Y
          nUA0kL3ppecMTlf24N3b9v+XMykkk8qwoA0dm4gC4l1j0VuHAV/Ljf838zSiwQ=

