---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: nginx-ingress
data:
  chart_name: ingress-nginx
  release: nginx-ingress
  namespace: kube-system
  wait:
    timeout: 1800
    labels:
      app.kubernetes.io/name: ingress-nginx
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
             app.kubernetes.io/name: ingress-nginx
  values:
    imagePullSecrets: [{"name": "default-registry-key"}]
    controller:
      kind: DaemonSet
      image:
        # cleans the default digest value since sysinv changes the digest when pushing the image to the local registry
        digest: ""
      daemonset:
        useHostPort: false
      nodeSelector:
        node-role.kubernetes.io/master: ""
      config:
        # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
        nginx-status-ipv4-whitelist: 0.0.0.0/0
        # See https://bugs.launchpad.net/starlingx/+bug/1823803
        # Note quotes are necessary.
        worker-processes: '1'
      scope:
        enabled: false
      service:
        type: ""
      hostNetwork: true
      livenessProbe:
        initialDelaySeconds: 30
      readinessProbe:
        initialDelaySeconds: 30
    defaultBackend:
      image:
        repository: k8s.gcr.io/defaultbackend
        tag: "1.4"
      nodeSelector:
        node-role.kubernetes.io/master: ""
      service:
        type: ""
      livenessProbe:
        initialDelaySeconds: 30
      readinessProbe:
        initialDelaySeconds: 30
  source:
    type: tar
    location: http://172.17.0.1/helm_charts/stx-platform/ingress-nginx-3.10.1.tgz
    subpath: ingress-nginx
    reference: master
  dependencies: []
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: nginx-ingress
data:
  description: "Deploy Nginx Ingress Controller"
  sequenced: false
  chart_group:
    - nginx-ingress
---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: nginx-ingress-controller-manifest
data:
  release_prefix: ic
  chart_groups:
    - nginx-ingress
